// Player pool for "What Tennis Hottie Are You?"
// Images live in /public/players/<slug>.jpg (sourced from Wikipedia / Wikimedia Commons).

export type TennisPlayer = {
  name: string;
  tour: 'ATP' | 'WTA';
  rank: number;
  image: string;
  why: string[];
  aura: string;
  redFlag: string;
  courtPersonality: string;
  doublesEnergy: string;
  funnyCaption: string;
};

export const PLAYERS: TennisPlayer[] = [
  // ATP
  {
    name: 'Jannik Sinner',
    tour: 'ATP',
    rank: 1,
    image: '/players/jannik-sinner.jpg',
    why: [
      'eerily calm under any amount of pressure',
      'redheaded protagonist of an anime',
      'doesn’t talk much but the racket does',
      'looks like he files his taxes early',
    ],
    aura: 'Quiet menace.',
    redFlag: 'never smiles until match point',
    courtPersonality: 'silent killer',
    doublesEnergy: 'lets the racket do the talking',
    funnyCaption: 'You got Jannik Sinner — terrifyingly composed.',
  },
  {
    name: 'Carlos Alcaraz',
    tour: 'ATP',
    rank: 2,
    image: '/players/carlos-alcaraz.jpg',
    why: [
      'chaotic golden retriever energy',
      'smiles before destroying opponents',
      'athletic but somehow still flirty',
      'probably says “lets goooo” unironically',
    ],
    aura: 'Dangerously fun.',
    redFlag: 'smashes rackets',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'carries the team',
    funnyCaption: 'You got Carlos Alcaraz — athletic, wild, always a good time.',
  },
  {
    name: 'Novak Djokovic',
    tour: 'ATP',
    rank: 3,
    image: '/players/novak-djokovic.jpg',
    why: [
      'has a 14-step pre-serve ritual',
      'won an argument before breakfast',
      'will outlast you in any conversation',
      'gluten free and proud of it',
    ],
    aura: 'Final boss.',
    redFlag: 'argues with the umpire about gravity',
    courtPersonality: 'cardio psychopath',
    doublesEnergy: 'wants to discuss strategy mid-rally',
    funnyCaption: 'You got Novak Djokovic — relentless and slightly intense.',
  },
  {
    name: 'Alexander Zverev',
    tour: 'ATP',
    rank: 4,
    image: '/players/alexander-zverev.jpg',
    why: [
      'towering and brooding',
      'serves like he’s mad at the ball',
      'main character with a complicated arc',
      'dresses like he’s late to a meeting',
    ],
    aura: 'Tall, dark, ace-y.',
    redFlag: 'sighs after every missed first serve',
    courtPersonality: 'silent killer',
    doublesEnergy: 'distractingly tall',
    funnyCaption: 'You got Sascha Zverev — ace machine with feelings.',
  },
  {
    name: 'Daniil Medvedev',
    tour: 'ATP',
    rank: 5,
    image: '/players/daniil-medvedev.jpg',
    why: [
      'stands at the back fence on purpose',
      'movements suggest a tall confused spider',
      'will out-think you for four hours',
      'big “I run on espresso and chaos” energy',
    ],
    aura: 'Octopus mode.',
    redFlag: 'mutters at the crowd',
    courtPersonality: 'cardio psychopath',
    doublesEnergy: 'poaches everything',
    funnyCaption: 'You got Daniil Medvedev — unhinged and effective.',
  },
  {
    name: 'Taylor Fritz',
    tour: 'ATP',
    rank: 6,
    image: '/players/taylor-fritz.jpg',
    why: [
      'California sunshine in human form',
      'serves bombs, vibes harder',
      'looks like he surfs between matches',
      'big “my girlfriend posts on TikTok” energy',
    ],
    aura: 'Golden state.',
    redFlag: 'too cool to look bothered',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'distractingly hot',
    funnyCaption: 'You got Taylor Fritz — Cali charm with a cannon serve.',
  },
  {
    name: 'Frances Tiafoe',
    tour: 'ATP',
    rank: 7,
    image: '/players/frances-tiafoe.jpg',
    why: [
      'the crowd is *yours*',
      'celebrations are personal artwork',
      'turns Tuesday matches into Broadway',
      'somehow always smiling mid-rally',
    ],
    aura: 'Showman.',
    redFlag: 'flirts between games',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'hypes the partner harder than the point',
    funnyCaption: 'You got Frances Tiafoe — entertainer first, tennis player second.',
  },
  {
    name: 'Tommy Paul',
    tour: 'ATP',
    rank: 8,
    image: '/players/tommy-paul.jpg',
    why: [
      'effortlessly stylish in a beat-up cap',
      'cardio that won’t quit',
      'low-key one of the most fun watches',
      'gives “coolest dad at the BBQ” vibes',
    ],
    aura: 'Quietly cool.',
    redFlag: 'plays it cool too well',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'covers half the court',
    funnyCaption: 'You got Tommy Paul — understated and undeniable.',
  },
  {
    name: 'Ben Shelton',
    tour: 'ATP',
    rank: 9,
    image: '/players/ben-shelton.jpg',
    why: [
      'serves measured in mph and vibes',
      'lefty energy unlocked',
      'fist pumps that could power a city',
      'protagonist of his own sports movie',
    ],
    aura: 'Lefty thunder.',
    redFlag: 'celebrates routine holds',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'serves all of them',
    funnyCaption: 'You got Ben Shelton — pure horsepower and grin.',
  },
  {
    name: 'Casper Ruud',
    tour: 'ATP',
    rank: 10,
    image: '/players/casper-ruud.jpg',
    why: [
      'wholesome Norwegian baseline metronome',
      'never misses a forehand or a thank-you note',
      'has emailed his coach already today',
      'shoulders weigh 6 grams',
    ],
    aura: 'Wholesome grinder.',
    redFlag: 'too polite to celebrate',
    courtPersonality: 'silent killer',
    doublesEnergy: 'apologizes constantly',
    funnyCaption: 'You got Casper Ruud — the nicest assassin on clay.',
  },
  {
    name: 'Holger Rune',
    tour: 'ATP',
    rank: 11,
    image: '/players/holger-rune.jpg',
    why: [
      'tantrum-to-talent ratio: high',
      'baby-faced absolute menace',
      'will argue with anyone, including himself',
      'fashion model in tennis kit',
    ],
    aura: 'Villain arc in progress.',
    redFlag: 'glares at his own box',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'might fight the umpire',
    funnyCaption: 'You got Holger Rune — gorgeous mess.',
  },
  {
    name: 'Stefanos Tsitsipas',
    tour: 'ATP',
    rank: 12,
    image: '/players/stefanos-tsitsipas.jpg',
    why: [
      'philosophy podcast in human form',
      'flowing hair, flowing thoughts',
      'reads a book between sets',
      'one-handed backhand, two-handed feelings',
    ],
    aura: 'Sigma philosopher.',
    redFlag: 'monologues during the changeover',
    courtPersonality: 'silent killer',
    doublesEnergy: 'tweets about it after',
    funnyCaption: 'You got Stef Tsitsipas — beautiful, brooding, baseline-y.',
  },
  {
    name: 'Andrey Rublev',
    tour: 'ATP',
    rank: 13,
    image: '/players/andrey-rublev.jpg',
    why: [
      'hits every ball like it owes him money',
      'screams encouragement at himself',
      '0% strategy, 200% effort',
      'thigh-slap legend',
    ],
    aura: 'Pure rage forehand.',
    redFlag: 'yells at his own thigh',
    courtPersonality: 'cardio psychopath',
    doublesEnergy: 'tries to hit through the net post',
    funnyCaption: 'You got Andrey Rublev — emotional support thigh-slapper.',
  },
  {
    name: 'Hubert Hurkacz',
    tour: 'ATP',
    rank: 14,
    image: '/players/hubert-hurkacz.jpg',
    why: [
      'six-foot-six of pure niceness',
      'serves so big the chair umpire flinches',
      'rallies last 2 shots, max',
      'gentle giant with rocket arm',
    ],
    aura: 'Gentle giant ace.',
    redFlag: 'ends points before you start them',
    courtPersonality: 'silent killer',
    doublesEnergy: 'just serves and grins',
    funnyCaption: 'You got Hubert Hurkacz — tallest sweetheart on tour.',
  },
  {
    name: 'Grigor Dimitrov',
    tour: 'ATP',
    rank: 15,
    image: '/players/grigor-dimitrov.jpg',
    why: [
      'aging like a fine cologne ad',
      'one-handed backhand straight from a museum',
      'looks like he plays for fun and wine',
      'main character in every changeover',
    ],
    aura: 'Vintage charm.',
    redFlag: 'dates within the tour',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'distractingly hot',
    funnyCaption: 'You got Grigor Dimitrov — aged like silk-screen prints.',
  },

  // WTA
  {
    name: 'Aryna Sabalenka',
    tour: 'WTA',
    rank: 1,
    image: '/players/aryna-sabalenka.jpg',
    why: [
      'roars after winners (and sometimes errors)',
      'every forehand is a personal threat',
      'big “gym in the morning, gym at night” energy',
      'hugs harder than she hits, somehow',
    ],
    aura: 'Pure power.',
    redFlag: 'celebrates every point at 100%',
    courtPersonality: 'cardio psychopath',
    doublesEnergy: 'carries the team',
    funnyCaption: 'You got Aryna Sabalenka — full send, every time.',
  },
  {
    name: 'Iga Swiatek',
    tour: 'WTA',
    rank: 2,
    image: '/players/iga-swiatek.jpg',
    why: [
      'noise-cancelling headphones are her best friend',
      'silently judges everyone and always shows up prepared',
      'has a routine for the routines',
      'topspin forehand straight from a textbook',
    ],
    aura: 'Quiet domination.',
    redFlag: 'won’t make eye contact pre-match',
    courtPersonality: 'silent killer',
    doublesEnergy: 'apologizes constantly',
    funnyCaption: 'You got Iga Swiatek — chillingly methodical.',
  },
  {
    name: 'Coco Gauff',
    tour: 'WTA',
    rank: 3,
    image: '/players/coco-gauff.jpg',
    why: [
      'cool under pressure',
      'secretly ultra competitive',
      'stylish without trying too hard',
      'gives “main character at the tournament” vibes',
    ],
    aura: 'Elite but approachable.',
    redFlag: 'owns 14 matching outfits',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'apologizes constantly',
    funnyCaption: 'You got Coco Gauff — effortlessly cool, always in the mix.',
  },
  {
    name: 'Elena Rybakina',
    tour: 'WTA',
    rank: 4,
    image: '/players/elena-rybakina.jpg',
    why: [
      'expression: unreadable. serve: 120 mph.',
      'main villain of a cool, quiet movie',
      'tall, blonde, statistically terrifying',
      'gives no clues whatsoever',
    ],
    aura: 'Stoic sniper.',
    redFlag: 'no celebration after aces',
    courtPersonality: 'silent killer',
    doublesEnergy: 'serves and never speaks',
    funnyCaption: 'You got Elena Rybakina — peak mystery, peak power.',
  },
  {
    name: 'Jessica Pegula',
    tour: 'WTA',
    rank: 5,
    image: '/players/jessica-pegula.jpg',
    why: [
      'low-key the most consistent person ever',
      'rich vibes, humble grind',
      'will out-pro you with zero drama',
      'sneakily one of the most-watched players',
    ],
    aura: 'Quietly elite.',
    redFlag: 'has 14 matching outfits but acts surprised',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'shows up prepared',
    funnyCaption: 'You got Jessica Pegula — chill on the outside, terminator inside.',
  },
  {
    name: 'Naomi Osaka',
    tour: 'WTA',
    rank: 6,
    image: '/players/naomi-osaka.jpg',
    why: [
      'soft-spoken, ground-stroke loud',
      'fashion icon with a cannon serve',
      'introvert with main-character outfits',
      'gives “please don’t talk to me at the breakfast buffet”',
    ],
    aura: 'Soft power.',
    redFlag: 'will not chat at the net',
    courtPersonality: 'silent killer',
    doublesEnergy: 'apologizes constantly',
    funnyCaption: 'You got Naomi Osaka — quietly devastating.',
  },
  {
    name: 'Mirra Andreeva',
    tour: 'WTA',
    rank: 7,
    image: '/players/mirra-andreeva.jpg',
    why: [
      'teenage prodigy with grandpa-level mind games',
      'sass-to-shots ratio: balanced',
      'celebrates with full-body sarcasm',
      'absolutely not intimidated',
    ],
    aura: 'Gen Z assassin.',
    redFlag: 'mock-claps the umpire',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'roasts the opponents (lovingly)',
    funnyCaption: 'You got Mirra Andreeva — 17 going on 30, ranked accordingly.',
  },
  {
    name: 'Qinwen Zheng',
    tour: 'WTA',
    rank: 8,
    image: '/players/qinwen-zheng.jpg',
    why: [
      'serve goes brrrr',
      'fearless against the top of the draw',
      'big “new boss appears” energy',
      'celebrates like she just won the world cup',
    ],
    aura: 'Rising thunder.',
    redFlag: 'fist pumps after warmup rallies',
    courtPersonality: 'cardio psychopath',
    doublesEnergy: 'carries the team',
    funnyCaption: 'You got Qinwen Zheng — main villain of the next final.',
  },
  {
    name: 'Jasmine Paolini',
    tour: 'WTA',
    rank: 9,
    image: '/players/jasmine-paolini.jpg',
    why: [
      'smiles through 3-hour grinders',
      'tiny in stature, enormous in heart',
      'will run down literally anything',
      'audience’s favorite human',
    ],
    aura: 'Pocket rocket joy.',
    redFlag: 'smiles too much (suspicious)',
    courtPersonality: 'cardio psychopath',
    doublesEnergy: 'carries the team',
    funnyCaption: 'You got Jasmine Paolini — joy with a backhand.',
  },
  {
    name: 'Madison Keys',
    tour: 'WTA',
    rank: 10,
    image: '/players/madison-keys.jpg',
    why: [
      'forehand mimics a small natural disaster',
      'class act with assassin tendencies',
      'big “quietly one of the best for a decade” energy',
      'underrated drip',
    ],
    aura: 'Big-hitting elegance.',
    redFlag: 'one shot away from blowing the doors off',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'carries the team',
    funnyCaption: 'You got Madison Keys — natural disaster, beautifully dressed.',
  },
  {
    name: 'Emma Navarro',
    tour: 'WTA',
    rank: 11,
    image: '/players/emma-navarro.jpg',
    why: [
      'will retrieve balls from another zip code',
      'looks polite, plays ruthless',
      'gives “library studyhall queen” vibes',
      'never says a word, just grinds',
    ],
    aura: 'Quiet grinder.',
    redFlag: 'apologizes after winners',
    courtPersonality: 'silent killer',
    doublesEnergy: 'apologizes constantly',
    funnyCaption: 'You got Emma Navarro — softest assassin on tour.',
  },
  {
    name: 'Daria Kasatkina',
    tour: 'WTA',
    rank: 12,
    image: '/players/daria-kasatkina.jpg',
    why: [
      'slice queen of mischief',
      'creative shots, creative content',
      'YouTube vlog brain in match form',
      'will dropshot you into therapy',
    ],
    aura: 'Trickster magic.',
    redFlag: 'dropshots on important points',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'poaches everything',
    funnyCaption: 'You got Dasha Kasatkina — slice, dice, and content.',
  },
  {
    name: 'Barbora Krejcikova',
    tour: 'WTA',
    rank: 13,
    image: '/players/barbora-krejcikova.jpg',
    why: [
      'doubles brain in singles body',
      'sneaky drop-volley specialist',
      'shows up at Slams and wins them',
      'lowkey one of the most well-rounded',
    ],
    aura: 'All-court craftsman.',
    redFlag: 'serve-and-volleys for fun',
    courtPersonality: 'silent killer',
    doublesEnergy: 'literal doubles champion',
    funnyCaption: 'You got Barbora Krejcikova — quietly does it all.',
  },
  {
    name: 'Karolina Muchova',
    tour: 'WTA',
    rank: 14,
    image: '/players/karolina-muchova.jpg',
    why: [
      'shot variety: yes, all of them',
      'gracefulness disguising violence',
      'one-handed slice + drop shot combo',
      'big “art student who fences competitively” vibes',
    ],
    aura: 'Elegant pickpocket.',
    redFlag: 'invents new shots mid-rally',
    courtPersonality: 'country club assassin',
    doublesEnergy: 'poaches everything',
    funnyCaption: 'You got Karolina Muchova — beautiful chaos.',
  },
  {
    name: 'Ons Jabeur',
    tour: 'WTA',
    rank: 15,
    image: '/players/ons-jabeur.jpg',
    why: [
      'Minister of Happiness™',
      'magician with the racket',
      'turns Slam finals into stand-up sets',
      'audience’s permanent crush',
    ],
    aura: 'Joyful trickster.',
    redFlag: 'dropshots on break point',
    courtPersonality: 'chaos gremlin',
    doublesEnergy: 'hypes everyone',
    funnyCaption: 'You got Ons Jabeur — pure joy with sneaky hands.',
  },
];

export const AURA_TAGLINES = [
  'Dangerously fun.',
  'Elite but approachable.',
  'Quiet menace.',
  'Pure power.',
];
