-- AUTO-GENERATED from nycgovparks.org/facilities/tennis (NYC Parks tennis directory).
-- Source script: scripts/build_nyc_parks_enrichment.py
-- Enriches existing nyc_parks rows (surface, court counts, indoor flag, notes,
-- park URL, accessibility) and inserts any NYC Parks facilities missing from the
-- tennismaps-derived seed (concession-run indoor tennis centers in particular).

-- 1. Schema additions (idempotent) ----------------------------------------
alter table hotties.facilities
  add column if not exists park_name text,
  add column if not exists park_url text,
  add column if not exists is_indoor boolean,
  add column if not exists accessible boolean,
  add column if not exists facility_notes text;

-- 2. nyc_parks source row (ensure present) --------------------------------
insert into hotties.sources (id, name, booking_url, scraper_type, enabled, notes) values
  ('nyc_parks', 'NYC Parks Tennis', 'https://www.nycgovparks.org/reg/tennis', 'nyc_parks_reg', false,
   'Citywide NYC Parks tennis reservation system. Permit-holder courts + concession-run indoor centers.')
on conflict (id) do update set
  name = excluded.name,
  booking_url = excluded.booking_url,
  notes = excluded.notes;

-- 3. Facilities upsert ----------------------------------------------------
insert into hotties.facilities
  (source_id, external_id, name, address, lat, lng, num_courts, surface,
   lights, active, category, region, phone, online_booking, facility_booking_url,
   metro, park_name, park_url, is_indoor, accessible, facility_notes)
values
  ('nyc_parks', 'nyc_parks:cary_leeds_tennis_center_at_crotona_park', 'Cary Leeds Tennis Center at Crotona Park', 'E. 173d St. and Crotona Ave.', null, null, 22, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 247-7420', true, 'http://www.nyjtl.org/caryleeds/', 'NYC', 'Crotona Park', 'https://www.nycgovparks.org/parks/crotona-park', true, true, 'Lessons are offered. During the indoor season (The day after Columbus Day – April 27), there are 10 outdoor courts available, and 10 courts are bubbled and can be rented for a fee. During the outdoor season, there are 15 courts available to Parks tennis permit holders. For booking courts and program information please call or visit Cary Leeds Tennis Center''s website for more information.'),
  ('nyc_parks', 'nyc_parks:governor_smith_playground', 'Governor Smith Playground', 'Morris Avenue between E. 151 and E. 153 Streets', null, null, 3, 'Hard', false, true, 'Public Managed', 'Bronx', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', null, null, false, false, null),
  ('nyc_parks', 'nyc_parks:haffen_park', 'Haffen Park', 'Hammersley, Ely, and Gunther Aves.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 379-8347', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Haffen Park', 'https://www.nycgovparks.org/parks/haffen-park', false, true, null),
  ('nyc_parks', 'nyc_parks:orchard_beach', 'Orchard Beach', '1 Orchard Beach Road', null, null, 4, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 885-3247', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Pelham Bay Park', 'https://www.nycgovparks.org/parks/pelham-bay-park', false, false, null),
  ('nyc_parks', 'nyc_parks:pelham_bay_park', 'Pelham Bay Park', 'Bruckner Blvd. and Middletown Rd.', null, null, 10, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 885-3442', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Pelham Bay Park', 'https://www.nycgovparks.org/parks/pelham-bay-park', false, false, null),
  ('nyc_parks', 'nyc_parks:seton_park', 'Seton Park', 'W. 232nd to 235th St., Palisade and Independence Aves.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 601-6044', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Seton Park', 'https://www.nycgovparks.org/parks/seton-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:st_james_park', 'St. James Park', 'Jerome Ave. and E. 193d St.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 822-4271', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'St. James Park', 'https://www.nycgovparks.org/parks/st-james-park', false, true, null),
  ('nyc_parks', 'nyc_parks:st_mary_s_park', 'St. Mary''s Park', 'E. 145 St. and St. Ann''s Ave.', null, null, 2, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 402-5161', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'St. Mary''s Park', 'https://www.nycgovparks.org/parks/st-marys-park', false, true, null),
  ('nyc_parks', 'nyc_parks:stadium_tennis_center_at_mill_pond_park', 'Stadium Tennis Center at Mill Pond Park', 'Gateway Center Boulevard (Exterior Street) and East 150th Street', null, null, 16, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 665-4684', true, 'http://www.stadiumtennisnyc.com/', 'NYC', 'Mill Pond Park', 'https://www.nycgovparks.org/parks/mill-pond-park', true, true, 'Lessons Offered. During the indoor season (The day after Columbus Day – April 27), there are 4 outdoor courts available, and 12 courts are bubbled and can be rented for a fee. During the outdoor season, 8 outdoor courts are available to Parks tennis permit holders. For booking courts and program information please call or visit the Stadium Tennis Center website for more information.'),
  ('nyc_parks', 'nyc_parks:van_cortlandt_park', 'Van Cortlandt Park', 'Stadium - W. 242nd St. and Broadway', null, null, 10, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 549-6494', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Van Cortlandt Park', 'https://www.nycgovparks.org/parks/VanCortlandtPark', false, true, null),
  ('nyc_parks', 'nyc_parks:van_cortlandt_park__woodlawn_w_233rd_st_jerom', 'Van Cortlandt Park', 'Woodlawn, W. 233rd St. & Jerome Ave.', null, null, 8, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 549-6494', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Van Cortlandt Park', 'https://www.nycgovparks.org/parks/VanCortlandtPark', false, true, null),
  ('nyc_parks', 'nyc_parks:williamsbridge_oval', 'Williamsbridge Oval', 'E. 208th St. and Bainbridge Ave.', null, null, 8, 'Hard', false, true, 'Public Managed', 'Bronx', '(718) 654-1851', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Williamsbridge Oval', 'https://www.nycgovparks.org/parks/williamsbridge-oval', false, false, null),
  ('nyc_parks', 'nyc_parks:bensonhurst_park', 'Bensonhurst Park', '9000 Bay Parkway, Brooklyn, NY 11214', null, null, 7, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 866-1031', true, 'https://matchpoint.nyc/our-clubs/bensonhurst/', 'NYC', 'Bensonhurst Park', 'https://www.nycgovparks.org/parks/bensonhurst-park', true, false, 'Note: Lessons are offered. All 7 courts are bubbled during the indoor season (Approximately, the day after Columbus Day through the last Friday in April) and may be rented for a fee. During the outdoor season, there are 6 courts available to Parks tennis permit holders. For bookings or for more information about tennis at Bensonhurst Park, please visit Matchpoint NYC.'),
  ('nyc_parks', 'nyc_parks:cooper_park_tennis_courts', 'Cooper Park Tennis Courts', 'Morgan Ave, between Maspeth Ave and Sharon St', null, null, 2, 'Hard', false, true, 'Public Managed', 'Brooklyn', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Cooper Park', 'https://www.nycgovparks.org/parks/cooper-park', false, false, null),
  ('nyc_parks', 'nyc_parks:decatur_playground', 'Decatur Playground', 'Decatur bet. Summer and Lewis Aves.', null, null, 1, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 493-7612', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Decatur Playground', 'https://www.nycgovparks.org/parks/decatur-playground', false, false, null),
  ('nyc_parks', 'nyc_parks:friends_field', 'Friends Field', 'Ave. L & East 4th St.', null, null, 2, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 965-6502', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Friends Field', 'https://www.nycgovparks.org/parks/friends-field', false, true, null),
  ('nyc_parks', 'nyc_parks:ft_greene_park', 'Ft. Greene Park', 'DeKalb & S. Portland Aves.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 722-3218', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Fort Greene Park', 'https://www.nycgovparks.org/parks/fort-greene-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:j_j_carty', 'J.J. Carty', '95 Street & Fort Hamilton Pkwy.', null, null, 10, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 439-4296', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'John J Carty Park', 'https://www.nycgovparks.org/parks/john-j-carty-park', false, false, null),
  ('nyc_parks', 'nyc_parks:jackie_robinson', 'Jackie Robinson', 'Malcolm X. Blvd. & Chauncey St.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 622-0025', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Jackie Robinson Park Playground', 'https://www.nycgovparks.org/parks/jackie-robinson-park_brooklyn', false, false, null),
  ('nyc_parks', 'nyc_parks:joseph_t_mcguire_park', 'Joseph T. McGuire Park', 'Avenue W and Bergen', null, null, 3, 'Hard', false, true, 'Public Managed', 'Brooklyn', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Mcguire Fields', 'https://www.nycgovparks.org/parks/joseph-t-mcguire-park', false, true, null),
  ('nyc_parks', 'nyc_parks:kaiser_playground', 'Kaiser Playground', 'Neptune Ave. & W. 25th St.', null, null, 12, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 946-1357', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Kaiser Park', 'https://www.nycgovparks.org/parks/leon-s-kaiser-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:kelly_playground', 'Kelly Playground', 'Ave. S & E.14th St.', null, null, 7, null, false, true, 'Public Managed', 'Brooklyn', '(718) 946-5913', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Kelly Park Playground', 'https://www.nycgovparks.org/parks/kelly-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:leif_ericson_park', 'Leif Ericson Park', '8th Ave. & 66th St.', null, null, 9, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 259-4016', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Leif Ericson Park', 'https://www.nycgovparks.org/parks/leif-ericson-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:lincoln_terrace_park', 'Lincoln Terrace Park', 'Buffalo & Rochester Aves.', null, null, 11, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 804-7077', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Lincoln Terrace / Arthur S. Somers Park', 'https://www.nycgovparks.org/parks/lincoln-terrace-arthur-s-somers-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:linden_playground', 'Linden Playground', 'Linden Blvd. & Vermont St.', null, null, 5, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 927-2059', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Linden Park', 'https://www.nycgovparks.org/parks/linden-park', false, false, null),
  ('nyc_parks', 'nyc_parks:lucille_ferrier_tennis_courts_dyker_beach_park', 'Lucille Ferrier Tennis Courts (Dyker Beach Park)', 'Cropsey Avenue, Bay 8th Street and Poly Place', null, null, 9, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 259-4016', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Dyker Beach Park', 'https://www.nycgovparks.org/parks/dyker-beach-park', false, true, null),
  ('nyc_parks', 'nyc_parks:manhattan_beach', 'Manhattan Beach', 'Oriental Blvd.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 646-5913', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Manhattan Beach Park', 'https://www.nycgovparks.org/parks/manhattan-beach-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:marine_park', 'Marine Park', 'Fillmore Ave. & Stuart St.', null, null, 15, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 376-1675', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Marine Park', 'https://www.nycgovparks.org/parks/marine-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:mccarren_tennis_center', 'McCarren Tennis Center', 'North 13th Street Between Berry Street and Bedford Avenue', null, null, 7, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(347) 873-9698', true, 'https://www.mccarrentennisnyc.com/', 'NYC', 'Mccarren Park', 'https://www.nycgovparks.org/parks/mccarren-park', true, false, 'Lessons are offered. All 7 courts are bubbled during the indoor season (the day after Columbus Day-April 27) and may be rented for a fee. During the outdoor season, there are 6 courts available to Parks tennis permit holders. For bookings or for more information about tennis at McCarren Park, please visit McCarren Tennis Center.'),
  ('nyc_parks', 'nyc_parks:mcdonald_avenue_playground', 'McDonald Avenue Playground', 'McDonald Ave. & Ave. S', null, null, 7, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 946-1373', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Mcdonald Playground', 'https://www.nycgovparks.org/parks/mcdonald-playground', false, false, null),
  ('nyc_parks', 'nyc_parks:mckinley_park', 'McKinley Park', '7th Ave. & 75th St.', null, null, 8, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 259-4016', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Mckinley Park', 'https://www.nycgovparks.org/parks/mckinley-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:one_van_voorhees_park', 'One Van Voorhees Park', 'Pacific, Congress and Hicks Streets', null, null, 2, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 722-3213', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Van Voorhees Playground', 'https://www.nycgovparks.org/parks/van-voorhees-park', false, false, null),
  ('nyc_parks', 'nyc_parks:prospect_park_tennis_center', 'Prospect Park Tennis Center', 'Parkside Ave at the Parade Ground', null, null, 11, 'Clay', false, true, 'Public Managed', 'Brooklyn', '(718) 436-2500', true, 'https://www.prospectpark.org/visit-the-park/places-to-go/tennis-center/', 'NYC', 'Prospect Park', 'https://www.nycgovparks.org/parks/prospect-park', true, false, 'Lessons are available. During the indoor season (October 23-May 6), there are 11 bubbled courts that may be rented for a fee. During the outdoor season, 8 courts are available to Parks tennis permit holders.  For more information, visit the Prospect Park Alliance tennis page.'),
  ('nyc_parks', 'nyc_parks:shore_road_playground', 'Shore Road Playground', 'Shore Rd. & 95th St.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Brooklyn', '(718) 259-4016', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Shore Park And Parkway', 'https://www.nycgovparks.org/parks/shore-park-and-parkway', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:south_oxford_park', 'South Oxford Park', 'Cumberland Street between Atlantic Commons and Atlantic Avenue', null, null, 2, 'Hard', false, true, 'Public Managed', 'Brooklyn', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'South Oxford Park', 'https://www.nycgovparks.org/parks/south-oxford-park', false, false, null),
  ('nyc_parks', 'nyc_parks:central_park', 'Central Park', '93d St. near West Drive', null, null, 4, 'Hard', false, true, 'Public Managed', 'Manhattan', '(212) 280-0206', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Central Park', 'https://www.nycgovparks.org/parks/central-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:central_park__93d_st_near_west_drive', 'Central Park', '93d St. near West Drive', null, null, 26, 'Fast Dry', false, true, 'Public Managed', 'Manhattan', '(212) 280-0206', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Central Park', 'https://www.nycgovparks.org/parks/central-park', false, false, null),
  ('nyc_parks', 'nyc_parks:fort_washington_park', 'Fort Washington Park', 'Hudson River at 170th St.', null, null, 10, 'Hard', false, true, 'Public Managed', 'Manhattan', '(212) 304-2322', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Fort Washington Park', 'https://www.nycgovparks.org/parks/fort-washington-park', false, false, 'Lessons offered by Riverside Tennis Association; sign up at RiversideTennis.org'),
  ('nyc_parks', 'nyc_parks:frederick_johnson_playground', 'Frederick Johnson Playground', 'Frederick Johnson Playground 151st St. east of 7th Ave.', null, null, 8, 'Hard', false, true, 'Public Managed', 'Manhattan', '(212) 234-9609', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', null, null, false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:howard_bennett_playground', 'Howard Bennett Playground', 'W. 136 St.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Manhattan', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Howard Bennett Playground', 'https://www.nycgovparks.org/parks/howard-bennett-playground', false, false, null),
  ('nyc_parks', 'nyc_parks:inwood_hill_park', 'Inwood Hill Park', '207th St. and Seaman Ave.', null, null, 9, 'Hard', false, true, 'Public Managed', 'Manhattan', '(212) 304-2381', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Inwood Hill Park', 'https://www.nycgovparks.org/parks/inwood-hill-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:pier_42', 'Pier 42', 'Pier 42 (near Pier 42) East River Greenway (South Side of FDR Dr. at Gouverneur St.)', null, null, 4, null, false, true, 'Public Managed', 'Manhattan', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Pier 42', 'https://www.nycgovparks.org/parks/pier-42', false, false, null),
  ('nyc_parks', 'nyc_parks:riverside_park', 'Riverside Park', 'Riverside Drive and W. 119th St.', null, null, 10, 'Hard', false, true, 'Public Managed', 'Manhattan', '(212) 408-0266', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Riverside Park', 'https://www.nycgovparks.org/parks/southernriverside-park', false, true, 'Lessons offered by Riverside Tennis Association; sign up at RiversideTennis.org'),
  ('nyc_parks', 'nyc_parks:riverside_park__riverside_drive_and_w_96th_st', 'Riverside Park', 'Riverside Drive and W. 96th St.', null, null, 10, 'Clay', false, true, 'Public Managed', 'Manhattan', '(212) 978-0277', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Riverside Park', 'https://www.nycgovparks.org/parks/southernriverside-park', false, false, 'Lessons offered by Riverside Tennis Association; sign up at RiversideTennis.org'),
  ('nyc_parks', 'nyc_parks:sportime_at_randall_s_island', 'Sportime at Randall''s Island', 'Randall''s Island Park', null, null, 24, 'Hard', false, true, 'Public Managed', 'Manhattan', '(212) 427-6150', true, 'https://www.sportimeny.com/manhattan', 'NYC', 'Randall''s Island Park', 'https://www.nycgovparks.org/parks/randalls-island', true, false, 'The Sportime Tennis Center is a concession offering half of its available courts to NYC Parks Tennis Permit holders during the outdoor season, which is from the Friday before Memorial Day through Labor Day. For more information, visit the Sportime Randall''s Island tennis page. Designated NYC Parks Courts:         Walk-ins only for designated NYC Parks courts and Online Reservation System for limited amount of courts to be reserved and paid ahead of time.    limited to one (1) hour for singles play, and two (2) hours for doubles play, although players may keep playing after their reserved times have ended if courts are available, upon confirming such availability with club staff.      All players using designated NYC Parks courts must affiliate with SPORTIME as an associate/non-member, and complete a waiver, prior to play. No Exceptions.    A reserved court is forfeited if the reserving player has not arrived by 5 minutes past the start time.'),
  ('nyc_parks', 'nyc_parks:sutton_tennis_at_queensboro_oval', 'Sutton Tennis at Queensboro Oval', 'York Ave. Between E 59 St. & E 60 St.', null, null, 8, 'Clay', false, true, 'Public Managed', 'Manhattan', '(212) 751-3452', true, 'https://www.suttoneasttennis.com', 'NYC', 'Queensboro Oval', 'https://www.nycgovparks.org/parks/queensboro-oval', true, true, 'Lessons are offered. Six courts are available to NYC Parks tennis permit holders from April 14 - September 14. For booking courts and program information please call or visit Sutton East Tennis Club''s website.'),
  ('nyc_parks', 'nyc_parks:washington_market_park', 'Washington Market Park', 'Chambers St. & West St.', null, null, 1, 'Hard', false, true, 'Public Managed', 'Manhattan', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Washington Market Park', 'https://www.nycgovparks.org/parks/washington-market-park', false, false, null),
  ('nyc_parks', 'nyc_parks:astoria_heights_playground', 'Astoria Heights Playground', 'Between 45th and 46th Street at 30th Road', null, null, 3, null, false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Astoria Heights Playground', 'https://www.nycgovparks.org/parks/astoria-heights-playground', false, false, null),
  ('nyc_parks', 'nyc_parks:astoria_park', 'Astoria Park', '21st St. & Hoyt Ave.', null, null, 14, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 626-8136', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Astoria Park', 'https://www.nycgovparks.org/parks/astoria-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:baisley_park', 'Baisley Park', '155th St. & 118th Ave.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Baisley Pond Park', 'https://www.nycgovparks.org/parks/baisley-pond-park', false, false, null),
  ('nyc_parks', 'nyc_parks:baisley_south', 'Baisley South', 'N. Conduit Ave. & 150th St.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Baisley Pond Park', 'https://www.nycgovparks.org/parks/baisley-pond-park', false, false, null),
  ('nyc_parks', 'nyc_parks:broad_channel_park', 'Broad Channel Park', 'Crossbay Blvd. and E. 16-E. 18 Rds.', null, null, 2, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 318-4000', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Broad Channel Park', 'https://www.nycgovparks.org/parks/broad-channel-park', false, false, null),
  ('nyc_parks', 'nyc_parks:brookville_park', 'Brookville Park', 'Brookville Blvd. & Southern Pkwy.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 255-2620', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Brookville Park', 'https://www.nycgovparks.org/parks/brookville-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:commonpoint_queens_tennis_and_athletic_center_at_alley_pond', 'Commonpoint Queens Tennis and Athletic Center at Alley Pond', 'Alley Athletic Playground Queens Village 79-20 Winchester Boulevard', null, null, 16, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 255-2127', true, 'https://www.commonpointqueens.org/hours-locations/tennis/', 'NYC', null, null, true, false, 'Lessons offered. During the indoor season (October - April), 11 courts are available to rent for a fee. During the outdoor season (May – September), 11 courts are available for Parks tennis permit holders. For booking courts and program information please call (718) 255-2127 or visit Commonpoint Queens Tennis and Athletic Center’s website.'),
  ('nyc_parks', 'nyc_parks:cunningham_tennis_center', 'Cunningham Tennis Center', 'Fresh Meadows 196-00 Union Turnpike', null, null, 20, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 740-6800', true, 'https://cunninghamtennis.com/', 'NYC', 'Cunningham Park', 'https://www.nycgovparks.org/parks/cunningham-park', true, false, 'Lessons offered. During the indoor/bubbled season, 10 courts are bubbled (The day after Columbus Day-April 27) and can be rented for a fee. During the Outdoor season 15 courts are available to Parks tennis permit holders. For booking courts and program information please call or visit the Cunningham Tennis website.'),
  ('nyc_parks', 'nyc_parks:det_keith_l_williams_park', 'Det. Keith L. Williams Park', 'Liberty Ave. & 173rd St.', null, null, 10, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Detective Keith L Williams Park', 'https://www.nycgovparks.org/parks/detective-keith-l-williams-park-liberty-park', false, true, null),
  ('nyc_parks', 'nyc_parks:east_elmhurst_ps_127', 'East Elmhurst (PS 127)', '25 Ave. & 98 St.-100 St.', null, null, 1, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 426-4347', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Helen Marshall Playground', 'https://www.nycgovparks.org/parks/helen-marshall-playground', false, false, null),
  ('nyc_parks', 'nyc_parks:flushing_fields_memorial', 'Flushing Fields Memorial', '149th St. & 25th Ave.', null, null, 8, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 359-1297', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Flushing Fields', 'https://www.nycgovparks.org/parks/flushing-fields', false, false, null),
  ('nyc_parks', 'nyc_parks:flushing_meadows_corona_park', 'Flushing Meadows Corona Park', 'Flushing Meadows Corona Park', null, null, 11, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 760-6999', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Flushing Meadows Corona Park', 'https://www.nycgovparks.org/parks/flushing-meadows-corona-park', false, true, null),
  ('nyc_parks', 'nyc_parks:forest_park', 'Forest Park', 'Park Lane South & 89th St.', null, null, 14, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 235-5871', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Forest Park', 'https://www.nycgovparks.org/parks/forest-park', false, true, null),
  ('nyc_parks', 'nyc_parks:highland_park_lower_playground', 'Highland Park- Lower Playground', 'Elton St. & Jamaica Ave.', null, null, 18, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 235-5871', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Highland Park', 'https://www.nycgovparks.org/parks/Q020', false, false, '10 full courts, 8 36-foot youth courts.'),
  ('nyc_parks', 'nyc_parks:juniper_valley_park', 'Juniper Valley Park', '62nd Ave. & 80th St.', null, null, 8, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 326-2877', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Juniper Valley Park', 'https://www.nycgovparks.org/parks/juniper-valley-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:kissena_park', 'Kissena Park', 'Rose & Oak Aves.', null, null, 8, 'Hartro', false, true, 'Public Managed', 'Queens', '(718) 359-1297', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Kissena Park', 'https://www.nycgovparks.org/parks/kissena-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:kissena_park__rose_oak_aves', 'Kissena Park', 'Rose & Oak Aves.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 359-1297', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Kissena Park', 'https://www.nycgovparks.org/parks/kissena-park', false, true, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:louis_pasteur_park', 'Louis Pasteur Park', '52 Ave. & Marathon Pkwy.', null, null, 2, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Louis Pasteur Park', 'https://www.nycgovparks.org/parks/louis-pasteur-park', false, false, null),
  ('nyc_parks', 'nyc_parks:maurice_park', 'Maurice Park', 'Maurice Ave., LIE Service Rd. Westbound', null, null, 2, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 326-2877', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Frank Principe Park', 'https://www.nycgovparks.org/parks/frank-principe-park', false, false, null),
  ('nyc_parks', 'nyc_parks:michaelis_bayswater_park', 'Michaelis Bayswater Park', '32nd St. & Dickens Ave.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 318-4000', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Bayswater Park', 'https://www.nycgovparks.org/parks/bayswater-park', false, false, null),
  ('nyc_parks', 'nyc_parks:police_officer_edward_byrne_park', 'Police Officer Edward Byrne Park', 'North Conduit Ave. & 134-135 Street', null, null, 4, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Police Officer Edward Byrne Park', 'https://www.nycgovparks.org/parks/police-officer-edward-byrne-park', false, false, null),
  ('nyc_parks', 'nyc_parks:rockaway_community_park', 'Rockaway Community Park', 'Alamdea Ave. btwn B51 & B56', null, null, 3, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 318-4000', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Rockaway Community Park', 'https://www.nycgovparks.org/parks/rockaway-community-park', false, false, null),
  ('nyc_parks', 'nyc_parks:roy_wilkins_park', 'Roy Wilkins Park', 'Merrick Blvd. & 119 Ave.', null, null, 4, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 276-8690', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Roy Wilkins Recreation Center', 'https://www.nycgovparks.org/parks/roy-wilkins-recreation-center', false, false, null),
  ('nyc_parks', 'nyc_parks:springfield_park', 'Springfield Park', '147 Ave. & Springfield Ave.', null, null, 2, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 225-2620', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Springfield Park', 'https://www.nycgovparks.org/parks/springfield-park', false, false, null),
  ('nyc_parks', 'nyc_parks:st_albans_park', 'St. Albans Park', 'Merrick Blvd. & 172nd St.', null, null, 2, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Archie Spigner Park', 'https://www.nycgovparks.org/parks/archie-spigner-park', false, false, null),
  ('nyc_parks', 'nyc_parks:victor_hanson_community_center_rochdale_park', 'Victor Hanson Community Center (Rochdale Park)', 'Guy Brewer Blvd. & 134th Ave.', null, null, 6, 'Hard', false, true, 'Public Managed', 'Queens', '(718) 978-1536', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Rochdale Park', 'https://www.nycgovparks.org/parks/rochdale-park', false, false, null),
  ('nyc_parks', 'nyc_parks:world_s_fair_playground', 'World''s Fair Playground', '62nd Drive & Grand Central Parkway Extension', null, null, 1, 'Hard', false, true, 'Public Managed', 'Queens', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Flushing Meadows Corona Park', 'https://www.nycgovparks.org/parks/flushing-meadows-corona-park', false, false, null),
  ('nyc_parks', 'nyc_parks:charles_kasper_tennis_courts', 'Charles Kasper Tennis Courts', 'Bard Ave. & Delafield Place', null, null, 6, 'All Weather', false, true, 'Public Managed', 'Staten Island', '(718) 667-3545', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Walker Park', 'https://www.nycgovparks.org/parks/walker-park', false, false, 'Lessons Offered'),
  ('nyc_parks', 'nyc_parks:fairview_park', 'Fairview Park', 'Bricktown Way, near parking lot', null, null, 2, 'Hard', false, true, 'Public Managed', 'Staten Island', null, true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Fairview Park', 'https://www.nycgovparks.org/parks/fairview-park', false, true, null),
  ('nyc_parks', 'nyc_parks:greenbelt_recreation_center', 'Greenbelt Recreation Center', '501 Brielle Avenue', null, null, 2, 'Hard', false, true, 'Public Managed', 'Staten Island', '(718) 667-3545', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Blood Root Valley', 'https://www.nycgovparks.org/parks/the-greenbelt', false, true, null),
  ('nyc_parks', 'nyc_parks:wolfe_s_pond_park', 'Wolfe''s Pond Park', 'Cornelia Ave., off of Hylan Blvd.', null, null, 2, 'All Weather', false, true, 'Public Managed', 'Staten Island', '(718) 667-3545', true, 'https://www.nycgovparks.org/reg/tennis', 'NYC', 'Wolfe''s Pond Park', 'https://www.nycgovparks.org/parks/wolfes-pond-park', false, true, 'Lessons Offered')
on conflict (source_id, external_id) do update set
  name = excluded.name,
  address = coalesce(excluded.address, hotties.facilities.address),
  num_courts = coalesce(excluded.num_courts, hotties.facilities.num_courts),
  surface = coalesce(excluded.surface, hotties.facilities.surface),
  category = excluded.category,
  region = excluded.region,
  phone = coalesce(excluded.phone, hotties.facilities.phone),
  online_booking = excluded.online_booking,
  facility_booking_url = excluded.facility_booking_url,
  metro = excluded.metro,
  park_name = coalesce(excluded.park_name, hotties.facilities.park_name),
  park_url = coalesce(excluded.park_url, hotties.facilities.park_url),
  is_indoor = coalesce(excluded.is_indoor, hotties.facilities.is_indoor),
  accessible = coalesce(excluded.accessible, hotties.facilities.accessible),
  facility_notes = coalesce(excluded.facility_notes, hotties.facilities.facility_notes);

-- Summary by borough:
--   Queens..............   27
--   Brooklyn............   23
--   Bronx...............   12
--   Manhattan...........   12
--   Staten Island.......    4